# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

# platform :ios do
#   desc "Run IOS tests"
#   lane :tests do
#     scan(
#       scheme: "rn_ci_cd"
#     )
#   end

#   desc "Build an App Store IPA"
#   lane :build_app_store do
#     build_app(
#       scheme: "rn_ci_cd",
#       workspace: "rn_ci_cd.xcworkspace",
#       export_method: "app-store"
#     )
#   end
#   desc "Build and upload to TestFlight"
#   lane :build_and_upload_to_testflight do
#     build_app(
#       scheme: "rn_ci_cd",
#       workspace: "rn_ci_cd.xcworkspace",
#       export_method: "testflight"
#     )
#   end
