# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  # Staging lane - for testing/QA (Internal Testing track)
  lane :staging do
    # AAB is already built in the previous step with incremented version
    # Just upload the existing AAB file to Internal Testing track
    upload_to_play_store(
      track: 'internal',
      release_status: 'completed',
      json_key: 'playstore-credentials.json',
      aab: 'app/build/outputs/bundle/release/app-release.aab'
    )
  end

  # Production lane - for main branch (Internal Testing track with draft)
  lane :playstore do
    # AAB is already built in the previous step with incremented version
    # Just upload the existing AAB file to Internal Testing track as draft
    upload_to_play_store(
      track: 'internal',
      release_status: 'completed',
      json_key: 'playstore-credentials.json',
      aab: 'app/build/outputs/bundle/release/app-release.aab'
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
